### ISSUE TITLE
Pin name of dist file (remove version, add entry to package.json)

### ISSUE THREAD

**Issue by sirlantis** [pebble/rockyjs#13]
#### Use Case
I use NPM as a dependency manager and luckily RockyJS is distributed via NPM.
I normally concatenate all my dependencies into a `libs.js` file (e.g. using Grunt).

#### Issue
The version suffix in the filename `rocky-0.1.0.js` forces me to update my Gruntfile whenever I update to the latest RockyJS. This shouldn't be necessary.

Note: It should also be listed as the `"main"` script in the `package.json` file. Should improve experience with Browserify or Webpack.

#### Discussion
The version of course makes sense for fixing the version when linking to it (the JSBin use case), but this should be handled on the GitHub page generation level (either querying NPM registry on iterating over the tags from the main repo):

```
mainRepo.tags
  .filter(looksLikeVersionTag)
  .forEach(tag => {
    let data = mainRepo.getFileAtCommit("dist/rocky.js", tag)
    writeToFile(`dist/rocky-${tag}.js`, data)
  })
```

#### Alternatives: Remove dist folder altogether

Maybe the `dist` folder shouldn't be kept in this repo at all.

Of course, this means if I change the dependency to a git dependency `dist/rocky.js` can't be found (I would have to go into that directory and run `grunt` myself). But this is not bad per se, as it will prevent me from including a stale `dist/rocky.js` (since it isn't re-generated after every single commit).

Scanning through some repos of libraries like jQuery/Angular/React nobody keeps the `dist` folder anymore.

**Comment by HBehrens** [comment]
With #30 we changed how we handle the versioning of `rocky.js`. When building locally, the resulting file is always named `build/dist/rocky.js` (without any suffix). The `package.json#main` refers to it that way, too.
On our gh-pages, we call this latest version `/dist/rocky-dev.js` to express its non-stable status. For each truly released version (e.g., those with a tag `0.1.0`) we keep a versioned copy at `dist/rocky-0.1.0.js` so that JSBins, etc. can refer to a stable version.

Does these cover your cases? If so, I'd like to close this issue.

**Comment by sirlantis** [comment]
:+1:
