### ISSUE TITLE
Community examples won't run.

### ISSUE THREAD

**Issue by ygalanter** [pebble/rockyjs#63]
Since link to community examples is HTTPS (https://pebble.github.io/rockyjs/examples/community.html) and iframes pointing to JSBIN sources are HTTP - due to mixed content examples don't load.
Either way it should match to load correctly (e.g. HTTP link http://pebble.github.io/rockyjs/examples/community.html works)

**Comment by HBehrens** [comment]
The problem is not so much mixed content (e.g. embedding HTTP into a HTTPS page) as one can replace specific links with `href="///jsbin.com"` to match the protocol. The issue is that JSBin requires you to have a pro account in order to make your bins embeddable via HTTPS and not every community member has.
Are you suggesting that we clone a bin with our RockyJS pro account before we embed it into the examples page?

**Comment by orviwan** [comment]
I thought perhaps the examples page could redirect to http automatically. https://github.com/pebble/rockyjs/pull/65/files

**Comment by ygalanter** [comment]
I think easiest way (since original examples embedded via HTTP anyway) simple make main link to running community examples also HTTP as well, I don't think there's a dire need for SSL here.
Another possibility - move community examples to https://jsfiddle.net/ I beleive their embeds are HTTPS

**Comment by orviwan** [comment]
A message has been added to the community examples page which also allows the user to redirect to http only.
